### ISSUE TITLE
[July 8th Meetup] Translate `library/pathlib.po`

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#443]
```[tasklist]
### Tasks
- [ ] [Title & Intro](https://docs.python.org/3/library/pathlib.html#module-pathlib) & [Basic use](https://docs.python.org/3/library/pathlib.html#module-pathlib) (15)
- [x] [Pure paths](https://docs.python.org/3/library/pathlib.html#pure-paths) (15)
- [ ] [General properties](https://docs.python.org/3/library/pathlib.html#general-properties), [Operators](https://docs.python.org/3/library/pathlib.html#operators), [Accessing individual parts](https://docs.python.org/3/library/pathlib.html#accessing-individual-parts) (13)
- [ ] [Methods and properties](https://docs.python.org/3/library/pathlib.html#methods-and-properties) `pathlib.rst:286` to `pathlib.rst:470` (25)
- [ ] [Methods and properties](https://docs.python.org/3/library/pathlib.html#methods-and-properties) `pathlib.rst:483` to `pathlib.rst:638` & [Concrete paths](https://docs.python.org/3/library/pathlib.html#concrete-paths) (21)
- [ ] [Methods](https://docs.python.org/3/library/pathlib.html#methods) `pathlib.rst:714` to `pathlib.rst:858` (18)
- [ ] [Methods](https://docs.python.org/3/library/pathlib.html#methods) `pathlib.rst:864` to `pathlib.rst:996` (20)
- [x] [Methods](https://docs.python.org/3/library/pathlib.html#methods) `pathlib.rst:1008` to `pathlib.rst:1158` (18)
- [ ] [Methods](https://docs.python.org/3/library/pathlib.html#methods) `pathlib.rst:1162` to `pathlib.rst:1279` & [Correspondence to tools in the os module](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) (20)
```

**Comment by Cliying94** [comment]
認領 [Title & Intro](https://docs.python.org/3/library/pathlib.html#module-pathlib) & [Basic use](https://docs.python.org/3/library/pathlib.html#module-pathlib) (15)

**Comment by weijay0804** [comment]
認領 [Pure paths](https://docs.python.org/3/library/pathlib.html#pure-paths) (15)

**Comment by Francescatai** [comment]
我要認領[General properties](https://docs.python.org/3/library/pathlib.html#general-properties)

**Comment by YellowElephantHive** [comment]
我要認領 library/pathlib.po [Methods and properties](https://docs.python.org/3/library/pathlib.html#methods-and-properties) pathlib.rst:286 to pathlib.rst:470 (25)

**Comment by sweslo17** [comment]
認領 [General properties](https://docs.python.org/3/library/pathlib.html#general-properties)

**Comment by poliyka** [comment]
認領 [Methods](https://docs.python.org/3/library/pathlib.html#methods) pathlib.rst:1008 to pathlib.rst:1158 (18)

**Comment by josix** [comment]
認領 by @englam [Methods](https://docs.python.org/3/library/pathlib.html#methods) pathlib.rst:1162 to pathlib.rst:1279 & [Correspondence to tools in the os module](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) (20)
