### ISSUE TITLE
[July 8th Meetup] Translate `library/venv.po`

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#444]
```[tasklist]
### Tasks
- [ ] [Title & Intro](https://docs.python.org/3/library/venv.html#module-venv) (6)
- [x] [Creating virtual environments](https://docs.python.org/3/library/venv.html#module-venv) (18)
- [ ] [How venvs work](https://docs.python.org/3/library/venv.html#how-venvs-work) (12)
- [ ] [API](https://docs.python.org/3/library/venv.html#how-venvs-work) `venv.rst:140` to `venv.rst:218` (15)
- [ ] [API](https://docs.python.org/3/library/venv.html#how-venvs-work) `venv.rst:225` to `venv.rst:299` (18)
- [ ] [API](https://docs.python.org/3/library/venv.html#how-venvs-work) `venv.rst:287` to `venv.rst:581` & [An example of extending EnvBuilder](https://docs.python.org/3/library/venv.html#an-example-of-extending-envbuilder)(16)
```

**Comment by jacksonchen1998** [comment]
認領 [Creating virtual environments](https://docs.python.org/3/library/venv.html#module-venv) (18)

**Comment by mattwang44** [comment]
認領 [How venvs work](https://docs.python.org/3/library/venv.html#how-venvs-work)

**Comment by maotingyang** [comment]
認領 [Title & Intro](https://docs.python.org/3/library/venv.html#module-venv) (6)

**Comment by rockleona** [comment]
認領 [API](https://docs.python.org/3/library/venv.html#how-venvs-work) venv.rst:140 to venv.rst:218 (15)

**Comment by AbyssDrake** [comment]
認領[ensurepip](https://docs.python.org/3/library/ensurepip.html)

**Comment by emily40830** [comment]
認領 [API](https://docs.python.org/3/library/venv.html#how-venvs-work) venv.rst:225 to venv.rst:299 (15)
