### ISSUE TITLE
Translate `library/socket.po` (Multiple)

### ISSUE THREAD

**Issue by weijay0804** [python/python-docs-zh-tw#611]
```[tasklist]
### Tasks
- [x] [intro](https://docs.python.org/3/library/socket.html#)
- [ ] [Socket families](https://docs.python.org/3/library/socket.html#socket-families)
- [ ] [Module contents](https://docs.python.org/3/library/socket.html#module-contents)
- [ ] [Module contents - Exceptions](https://docs.python.org/3/library/socket.html#exceptions)
- [ ] [Module contents - Constants](https://docs.python.org/3/library/socket.html#constants)
- [ ] [Module contents - Functions](https://docs.python.org/3/library/socket.html#functions)
- [ ] [Module contents - Creating sockets](https://docs.python.org/3/library/socket.html#creating-sockets)
- [ ] [Module contents - Other functions](https://docs.python.org/3/library/socket.html#other-functions)
- [ ] [Socket Objects](https://docs.python.org/3/library/socket.html#socket-objects)
- [ ] [Notes on socket timeouts](https://docs.python.org/3/library/socket.html#notes-on-socket-timeouts)
- [ ] [Notes on socket timeouts - Timeouts and the connect method](https://docs.python.org/3/library/socket.html#timeouts-and-the-connect-method)
- [ ] [Notes on socket timeouts - Timeouts and the accept method](https://docs.python.org/3/library/socket.html#timeouts-and-the-accept-method)
- [ ] [Example](https://docs.python.org/3/library/socket.html#example)
```
