### ISSUE TITLE
Translate `library/decimal.po`

### ISSUE THREAD

**Issue by 0gien** [python/python-docs-zh-tw#690]
```[tasklist]
### Tasks
- [ ] Quick-start Tutorial
- [ ] `Decimal` objects
- [ ] Context objects
- [ ] Constants
- [ ] Signals
- [ ] Floating Point Notes
- [ ] Working with threads
- [ ] Recipes
- [ ] `Decimal` FAQ
```
